version: "3.8"

services:

  mongo:
    image: mongo:4.4
    env_file: mongo.env
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=MONGO_DB_ROOT_USERNAME"
      - "MONGODB_INITDB_ROOT_PASSWORD=MONGO_DB_ROOT_PASSWORD"
    volumes:
      - "/mongo-data/mongo/db"

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
      restart: always
      container_name: elasticsearch
      ports:
       - "9200:9200"
       - "9300:9300"
      environment: 
        - cluster.name= cti-dev
        - xpack.security.enabled=false
        - discovery.type= single-node
      volumes:
        - "esdata:/usr/share/elasticsearch/data"
      networks: 
        - elastic
 
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    restart: always
    container_name: kibana
    env_file: elastic.env
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=ELASTIC_URL"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    
  squid:
    image: ubuntu/squid:latest
    container_name: squid_proxy
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./squid/passwords:/etc/squid/passwords
    restart: always

volumes:
  mysql_data:
  esdata:
    driver: local

networks:
  elastic:
    driver: bridge

          