version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INIT_DB_ROOT_USERNAME=${MONGO_INIT_DB_ROOT}"
      - "MONGO_INIT_DB_ROOT_PASSWORD=${MONGO_INIT__DB_ROOT_PASSWORD}"
    volumes:
      - "./mongo-data/mongo/db"

  redis:
    image: redis:latest
    container_name: redis

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    volumes:
      - "mysql_data:/var/lib/mysql"

 # Snippet code from https://github.com/coolacid/docker-misp
    misp:
      image: coolacid/misp-docker:core-latest
      restart: always
      container_name: misp
      depends_on:
        - redis
        - mysql
      ports:
        - "80:80"
        - "443:443"
      environment:
        - "HOSTNAME=${MISP_HOSTNAME}"
        - "INIT=true"
        - "CRON_USER_ID=1"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        - "MYSQL_ROOT_PASSWORD={MYSQL_ROOT_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      volumes:
       - "./misp-conf/var/www/MISP/app/Config/"
       - "./misp-logs/var/www/MISP/app/tmp/logs"
       - "./files/:var/www/MISP/app/files"

    misp-modules:
      image: coolacid/misp-docker:modules-latest
      container_name: misp-modules
      environment:
        - "REDIS_BACKEND=redis"
      depends_on:
        - redis
        - mysql

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:latest
      restart: always
      container_name: elasticsearch
      ports:
       - "9200:9200"
       - "9300:9300"
      environment: 
        - "xpack.security.enabled=false"
        - "discovery.type=single-node"
      volumes:
        - "esdata:/usr/share/elasticsearch/data"
 
  kibana:
    image: docker.elastic.co/elasticsearch/kibana:latest
    restart: always
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=${ELASTICSEARCH_URL}"
      - "ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}"
    depends_on:
      - elasticsearch
    
  squid:
    image: ubuntu/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./squid/passwords:/etc/squid/passwords
    restart: always


  celery_worker:
    build:
      context: .
    depends_on:
      - redis
      - mongo
      
  celery_beat:
    build: 
     context: .
    depends_on:
      - redis
      - mongo


volumes:
  mysql_data:
  esdata:
    driver: local

          