version: "3.8"

services:

  mail:
    image: namshi/smtp
    container_name: misp_smtp_server

  mongo:
    image: mongo:4.4
    env_file: mongo.env
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - "MONGODB_INITDB_ROOT_USERNAME=MONGO_DB_ROOT_USERNAME"
      - "MONGODB_INITDB_ROOT_PASSWORD=MONGO_DB_ROOT_PASSWORD"
    volumes:
      - "/mongo-data/mongo/db"

  redis:
    image: redis:latest
    container_name: redis

  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: mysql.env
    restart: always
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_USER=USER"
      - "MYSQL_PASSWORD=PASSWORD"
      - "MYSQL_ROOT_PASSWORD=ROOT_PASSWORD"
      - "MYSQL_DATABASE=DATABASE"
    volumes:
      - "mysql_data:/var/lib/mysql"

 # Snippet code from https://github.com/coolacid/docker-misp
  misp:
    image: coolacid/misp-docker:core-latest
    restart: always
    env_file: 
      - misp.env
      - mysql.env
    container_name: misp
    depends_on:
      - redis
      - mysql
      - mail
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "MISP_BASEURL=MISP_HOSTNAME"
      - "INIT=true"
      - "CRON_USER_ID=1"
      - "MYSQL_USER=USER"
      - "MYSQL_PASSWORD=PASSWORD"
      - "MYSQL_DATABASE=DATABASE"
    volumes:
     - "./misp-conf/var/www/MISP/app/Config/"
     - "./misp-logs/var/www/MISP/app/tmp/logs"
     - "./files/:var/www/MISP/app/files"

  misp-modules:
    image: coolacid/misp-docker:modules-latest
    container_name: misp-modules
    env_file: misp.env
    environment:
       - "REDIS_BACKEND=REDIS_BACKEND"
    depends_on:
      - redis
      - mysql

  esnode1:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
      restart: always
      container_name: elastic-cti-node01
      ports:
       - "9200:9200"
       - "9300:9300"
      environment: 
        - "cluster.name=cti-data-prod"
        - "node.name=cti-node01"
        - "discovery.seed_hosts=cti-node01,cti-node02"
        - "xpack.security.enabled=true"
        - "xpack.monitoring.collection.enabled=true"
        - "ES_JAVA_OPTS=Xms512m -Xmx512m"
        - "bootstrap.memory_lock=true"
      ulimitis:
        memlock:
          soft: -1
          hard: -1
      volumes:
        - "esdata1:/usr/share/elasticsearch/data"
      networks: 
        - elastic

  esnode2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    restart: always
    container_name: elastic-cti-node02
    environment: 
      - "cluster.name=cti-data-prod"
      - "cluster.initial_master_nodes=cti-node01,cti-node02,cti-node03"
      - "node.name=cti-node02"
      - "discovery.seed_hosts=cti-node01,cti-node02"
      - "xpack.security.enabled=true"
      - "xpack.monitoring.collection.enabled=true"
      - "ES_JAVA_OPTS=Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
    ulimitis:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "esdata2:/usr/share/elasticsearch/data"
    networks: 
        - elastic

  esnode3:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    restart: always
    container_name: elastic-cti-node03
    environment: 
      - "cluster.name=cti-data-prod"
      - "node.name=cti-node03"
      - "discovery.seed_hosts=cti-node01,cti-node02"
      - "cluster.initial_master_nodes=cti-node01,cti-node02,cti-node03"
      - "xpack.security.enabled=true"
      - "xpack.monitoring.collection.enabled=true"
      - "ES_JAVA_OPTS=Xms512m -Xmx512m"
      - "bootstrap.memory_lock=true"
    ulimitis:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "esdata3:/usr/share/elasticsearch/data"
    networks: 
       - elastic
 
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.2
    restart: always
    container_name: kibana
    env_file: elastic.env
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=ELASTIC_URL"
      - "ELASTICSEARCH_HOSTS=[http://cti-node01:9200,http://cti-node02:9200,http://cti-node03:9200]"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    
  squid:
    image: ubuntu/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./squid/squid.conf:/etc/squid/squid.conf
      - ./squid/passwords:/etc/squid/passwords
    restart: always


  celery_worker:
    build:
      context: .
    depends_on:
      - redis
      - mongo
      
  celery_beat:
    build: 
     context: .
    depends_on:
      - redis
      - mongo


volumes:
  mysql_data:
  esnode1:
    driver: local
  esnode2:
    driver: local
  esnode3:
    driver: local

  network:
    elastic:
      driver: bridge

          