# Generated by Django 4.1.7 on 2023-05-02 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('type', models.CharField(max_length=128, verbose_name='type')),
                ('value', models.TextField(blank=True, verbose_name='value')),
                ('required', models.BooleanField(verbose_name='required')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation_date')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update_date')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='name')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation_date')),
            ],
        ),
    ]
