# Generated by Django 4.1.7 on 2023-03-25 16:34

import data_collector.models
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(max_length=128)),
                ('value', models.TextField(blank=True)),
                ('required', models.BooleanField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DataFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True)),
                ('name', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('format_type', models.CharField(choices=[('Yara', 'Yara'), ('STIX', 'Stix'), ('SIGMA', 'Sigma'), ('Suricata', 'Suricata'), ('Open_IOC', 'Open Ioc'), ('MISP', 'Misp'), ('Other', 'Other')], default='Other', max_length=128)),
                ('elements', djongo.models.fields.ArrayField(model_container=data_collector.models.DataFeedElement)),
            ],
        ),
    ]
