# Generated by Django 4.1.7 on 2023-03-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafeed',
            old_name='type',
            new_name='format_type',
        ),
    ]
