# Generated by Django 4.1.7 on 2023-03-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='value',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
