# Generated by Django 4.1.7 on 2023-03-08 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeed',
            name='feed_data_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 18, 58, 48, 791967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='datafeeditem',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 18, 58, 48, 791967, tzinfo=datetime.timezone.utc)),
        ),
    ]
