# Generated by Django 4.1.7 on 2023-03-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_rename_type_datafeed_format_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiconfig',
            name='value',
            field=models.TextField(blank=True, max_length=128),
        ),
    ]
