# Generated by Django 4.1.7 on 2023-05-11 10:37

from django.db import migrations
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='collector',
            field=djongo.models.fields.ArrayReferenceField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='data_collector.feed'),
            preserve_default=False,
        ),
    ]
