# Generated by Django 4.1.7 on 2023-05-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0003_index_collector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='collector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collector.feed'),
        ),
    ]
