# Generated by Django 4.1.7 on 2024-02-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0005_alter_index_collector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfig',
            name='type',
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_collector.feed'),
        ),
        migrations.AlterField(
            model_name='apiconfig',
            name='name',
            field=models.CharField(max_length=126, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='DailyIndexMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('index_size', models.DecimalField(decimal_places=5, default=0, max_digits=5)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collector.feed')),
            ],
        ),
    ]
