# Generated by Django 4.1.7 on 2024-02-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0006_remove_apiconfig_type_apiconfig_collector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyindexmetadata',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_collector.index'),
        ),
    ]
