# Generated by Django 4.1.7 on 2023-03-08 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0008_alter_datafeed_feed_data_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafeed',
            name='feed_data_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 18, 59, 40, 382551, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='datafeeditem',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 8, 18, 59, 40, 382551, tzinfo=datetime.timezone.utc)),
        ),
    ]
