# Generated by Django 4.1.7 on 2023-03-15 20:38

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0011_alter_datafeed_feed_data_creation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.TextField(max_length=128)),
                ('type', models.TextField(max_length=128)),
                ('value', models.TextField(max_length=128)),
                ('required', models.BooleanField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='datafeed',
            name='collector',
        ),
        migrations.AlterField(
            model_name='datafeed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datafeed',
            name='feed_data_creation',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 20, 38, 42, 989901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='datafeeditem',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 15, 20, 38, 42, 989901, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='DataCollector',
        ),
        migrations.DeleteModel(
            name='DataCollectorSecret',
        ),
    ]
