# Generated by Django 4.1.7 on 2023-03-16 14:43

import data_collector.sources.models
from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeed',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('elements', djongo.models.fields.ArrayField(model_container=data_collector.sources.models.DataFeedElement)),
            ],
        ),
        migrations.CreateModel(
            name='DataFeedElement',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.JSONField(blank=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
