# Generated by Django 4.1.7 on 2023-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafeed',
            name='source',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
